// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASZKrDKkeU9KN4GiuaG3rjJ-jNDPTp6o8',
    appId: '1:34142689471:web:bbd61f0a45c7fd1d1e8e0a',
    messagingSenderId: '34142689471',
    projectId: 'app-flutter-pet-shop',
    authDomain: 'app-flutter-pet-shop.firebaseapp.com',
    storageBucket: 'app-flutter-pet-shop.appspot.com',
    measurementId: 'G-E6VC9NS5SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtX5nTPxAbwWx3RzjwSkOhnNTFOBpIH4M',
    appId: '1:34142689471:android:555f0769c6c30fc11e8e0a',
    messagingSenderId: '34142689471',
    projectId: 'app-flutter-pet-shop',
    storageBucket: 'app-flutter-pet-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5hcAsBH5kvaN4iHf_-cVtJ-GnZ0tVoz0',
    appId: '1:34142689471:ios:603b6d7b4e3e76401e8e0a',
    messagingSenderId: '34142689471',
    projectId: 'app-flutter-pet-shop',
    storageBucket: 'app-flutter-pet-shop.appspot.com',
    iosBundleId: 'com.example.flutterProjectstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5hcAsBH5kvaN4iHf_-cVtJ-GnZ0tVoz0',
    appId: '1:34142689471:ios:603b6d7b4e3e76401e8e0a',
    messagingSenderId: '34142689471',
    projectId: 'app-flutter-pet-shop',
    storageBucket: 'app-flutter-pet-shop.appspot.com',
    iosBundleId: 'com.example.flutterProjectstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASZKrDKkeU9KN4GiuaG3rjJ-jNDPTp6o8',
    appId: '1:34142689471:web:3d5c2eb1db279d021e8e0a',
    messagingSenderId: '34142689471',
    projectId: 'app-flutter-pet-shop',
    authDomain: 'app-flutter-pet-shop.firebaseapp.com',
    storageBucket: 'app-flutter-pet-shop.appspot.com',
    measurementId: 'G-F1J7YFP055',
  );
}
